### ISSUE TITLE
Tabindex not working

### ISSUE THREAD

**Issue by pimvdnoll** [mendix/RadiobuttonList#10]
I used this widget in a signup form with explicit use of tabindexes (because some browsers don't understand if you let the tabindex empty..Internet explorer..).
taborder is not working and will stuck at the widget

**Comment by GREdens** [comment]
The mendix client api for custom widgets as far as i know does not support setting or getting the current tabindex of the widget to begin with. That means it is impossible to guess the tabindex where the radiobuttonlist should start and end with. That is why unfortunately we cannot implement this feature. Fixing this would also mean implementing something for this inside the mendix client api. You can create a support feature request ticket for this.
