### ISSUE TITLE
Access rights Read

### ISSUE THREAD

**Issue by sebasvanderplaat** [mendix/RadiobuttonList#11]
Hi, It looks like this issue has already been fixed looking at the release notes. I just downloaded the latest version of the radio buttonList and I see that it's not fixed. 

The situation:

I have a form which should be not editable when status is completed. This is defined on entity level. For the multi reference tick box selector it works fine, but unfortunately for the radiobuttonList it doesn't. My fields are still shown as editable. When I change them and press save I (of course) get an error

**Comment by RoelandSalij** [comment]
Fixed in v6.0
