### ISSUE TITLE
Focus is lost after object refresh

### ISSUE THREAD

**Issue by dson** [mendix/RadiobuttonList#19]
In the AttrRadioButtonList widget, new radio button nodes are created on every update. This is not necessary since the enumeration or boolean values never change during the lifespan of the widget. The problem with recreating the radio button nodes is that if a radio button has the focus and the object is refreshed (e.g. by an onchange microflow) it loses the focus as it is replaced with a new node.

**Comment by JelteMX** [comment]
Can you test [this version](https://github.com/mendix/RadiobuttonList/raw/bugfix/focus-lost-attrradiobuttonlist/test/Widgets/RadioButtonList.mpk) and see if this solves your problem?

**Comment by Andries-Smit** [comment]
Stale issue. quick fix was implemented, tough rebuild is advisable. Suggested to this with the new Pluggable widget AP, when it supports data sources.
