### ISSUE TITLE
Unhandled promise rejection & update datasource mf when context object refreshes

### ISSUE THREAD

**Issue by stephanbruijnis** [mendix/RadiobuttonList#28]
Hi, 

I've a similar/same issue as described in the SimpleCheckboxSetSelector widget.

A radiobuttonlist widget is added to the page.
- Datasource = microflow
- Mendix 7.13.1
- latest appstore version of widget

When page opens and no objects are returned in the datasource microflow the page won't open but throw a Unhandled promise rejection TypeError: "objs is null" in the browser and server. The page will keep showing the loading bar.

I would also expect the widget to update the data source MF when the context object refreshes.  But the DataSource microflow is not called again when context object is refreshed

**Comment by JelteMX** [comment]
Please test [this version](https://github.com/mendix/RadiobuttonList/raw/bugfixing_tickets/dist/RadioButtonList.mpk) and report back if this fixes the issue

**Comment by stephanbruijnis** [comment]
Thanks for the new version I'll test it next week (just came back from holiday) and keep you updated.

**Comment by stephanbruijnis** [comment]
Works like a charm, thank you Jelte!

**Comment by JelteMX** [comment]
Fixed and released in [6.4.3](https://github.com/mendix/RadiobuttonList/releases/tag/v6.4.3)
