### ISSUE TITLE
Unhandled promise rejection "this.inputNodes is null" when navigation away from page

### ISSUE THREAD

**Issue by JelleDekker** [mendix/RadiobuttonList#29]
Case:
- Mendix 7.15.1
- Page with editable listview containing "Association Radiobutton List" (datasource listview = association)
- When navigating away from the page using a microflow (action "Show page") the following error is shown:
![image](https://user-images.githubusercontent.com/1491873/41701791-0525f6ec-752e-11e8-8d85-c6227953e3ee.png)

Note: error does not seem to occur when the Microflow does Close page first and then Show page

**Comment by rrachuri** [comment]
Hello,

We are seeing the above error in 7.16 version.  Can you please let me know when you are planning to release fix for the above issue?

Thank you

**Comment by Andries-Smit** [comment]
Fixed in https://github.com/mendix/RadiobuttonList/releases/tag/v7.0.0
