### ISSUE TITLE
null error on inputNodes on assocradiolist

### ISSUE THREAD

**Issue by reekers** [mendix/RadiobuttonList#34]
In a specific situation we get an error on inputNodes being null. It's pretty hard to reproduce, but my guess is that the interface wants to render before the association is filled. It seems to happen when an executed microflow takes xxx ms too long, although I cannot back this up by measurements...

Anyway, fixed this for our specific situation and will create a merge request

**Comment by JelteMX** [comment]
Tested and implemented in [6.4.4](https://github.com/mendix/RadiobuttonList/releases/tag/v6.4.4), thanks for the fix. Released in the App Store
